[tool.poetry]
name = "convai"
package-mode = false

[tool.poetry.dependencies]
python = "^3.8"
elevenlabs = { version = "^1.11.0", extras = ["pyaudio"] }

[tool.poetry.scripts]
demo = "convai.demo:main"
